### ISSUE TITLE
Error: Invalid login: 502 Command not implemented

### ISSUE THREAD

**Issue by saostad** [Youans/nodejs-nodemailer-outlook#5]
Hi,

I have tried to use this package but it is giving me this error message:

```
Error: Invalid login: 502 Command not implemented
    at SMTPConnection._formatError (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:605:19)
    at SMTPConnection._actionAUTHComplete (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:1340:34)
    at SMTPConnection.<anonymous> (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:378:26)
    at SMTPConnection._processResponse (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:764:20)
    at SMTPConnection._onData (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:570:14)
    at Socket.<anonymous> (C:\Users\SOstad\Projects\ad-companies\node_modules\nodemailer\lib\smtp-connection\index.js:522:47)
    at Socket.emit (events.js:196:13)
    at Socket.EventEmitter.emit (domain.js:471:20)
    at addChunk (_stream_readable.js:290:12)
    at readableAddChunk (_stream_readable.js:271:11) {
  code: 'EAUTH',
  response: '502 Command not implemented',
  responseCode: 502,
  command: 'AUTH PLAIN'
}
```

**Comment by Youans** [comment]
Probably you have not correctly added your authentication, I have updated the readme file + the test case file for more readability and it ran fine with me check https://github.com/Youans/nodejs-nodemailer-outlook/blob/master/test/app.js

**Comment by saostad** [comment]
Problem solved. it was a firewall problem
